apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-operator-helm
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bookstore-operator-helm
  template:
    metadata:
      labels:
        name: bookstore-operator-helm
    spec:
      serviceAccountName: bookstore-operator-helm
      containers:
        - name: bookstore-operator-helm
          # Replace this with the built image name
          image: davidmachacek/bookstore-operator-helm:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "bookstore-operator-helm"
