apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bookstoreansibles.david.com
spec:
  group: david.com
  names:
    kind: BookStoreAnsible
    listKind: BookStoreAnsibleList
    plural: bookstoreansibles
    singular: bookstoreansible
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1
    served: true
    storage: true
