apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bookstores.velotio.com
spec:
  group: velotio.com
  names:
    kind: BookStore
    listKind: BookStoreList
    plural: bookstores
    singular: bookstore
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
